version: '3.8'


services:
  scheduler_ui:
    build:
      context: .
      dockerfile: DOCKERFILE
      args:
        SERVER_ENDPOINT: ${SERVER_ENDPOINT}
    container_name: scheduler_ui
    env_file: .env
    restart: always
    ports:
      - "8096:80"
