# build environment
FROM node:18 AS build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
RUN npm config set maxsockets=5 # this is to avoid issues with slow unreliable internet connections
#COPY package-lock.json ./
RUN npm i --no-package-lock
COPY . ./
RUN npm run build

# production environment
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

ARG SERVER_ENDPOINT
ENV SERVER_ENDPOINT=$SERVER_ENDPOINT
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf.template
RUN sed -i "s@\$SERVER_ENDPOINT@${SERVER_ENDPOINT}@g" /etc/nginx/conf.d/default.conf.template
RUN mv /etc/nginx/conf.d/default.conf.template /etc/nginx/conf.d/default.conf

EXPOSE 80

# Copy .env file and shell script to container
WORKDIR /usr/share/nginx/html

# Add bash
RUN apk add --no-cache bash

CMD ["/bin/bash", "-c", " nginx -g \"daemon off;\""]
